skills/config/routes.rb
Skills::Application.routes.draw do
  resources :skills

  root 'welcome#index'

  

end

skills/app/models/skill.rb
class Skill < ActiveRecord::Base
end

skills/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @skill }
      else
        format.html { render action: 'new' }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :level, :description)
    end
end

skills/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@skills = Skill.all
	end
end

skills/app/helpers/skills_helper.rb
module SkillsHelper
end

skills/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skills</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

skills/app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skills/app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

skills/app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.level %></td>
        <td><%= skill.description %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

skills/app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

skills/app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @skill.level %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skill.description %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

skills/app/views/welcome/index.html.erb
<div id="container"> 

	<img src="../assets/me.jpg" alt = this is a kitten>

	<div id="content">
		<h1>Hi, I'm Alyssa</h1>
		<p>
			I like to create and build. I like building products, organizations, friendships, and change. I'm from San Francisco - born and raised in our fair city by the bay. I <a href="http://www.kontagent.com/"> work</a> and <A HREF="https://maps.google.com/maps?q=duboce+triangle&ie=UTF-8&hq=&hnear=0x808f7e1dd3d55b73:0x711a5eba2b5e2c64,Duboce+Triangle,+San+Francisco,+CA&gl=us&ei=KtBRUujZD4GriAKD1oDQBw&ved=0CKUBELYD"> live</A> here now too. I love to travel, <a href="http://www.lightstalkers.org/images/show/125253"> take pictures</a>, and grow ideas. Professionally, I'm a budding product gal, working the the start-up world. I'm learning to code. 
		</p>
		<div id="skills">
			<h2>My Skills</h2>
			<ul>
				<% @skills.each do |skill| %>
					<li> <%= link_to skill.name, skill %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>