moneybags/config/routes.rb
Moneybags::Application.routes.draw do
  resources :spaces

  root 'welcome#index'

  

end

moneybags/app/models/space.rb
class Space < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :cost
end

moneybags/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

moneybags/app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render action: 'show', status: :created, location: @space }
      else
        format.html { render action: 'new' }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :cost)
    end
end

moneybags/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
@spaces = Space.all
	end
end

moneybags/app/helpers/application_helper.rb
module ApplicationHelper
end

moneybags/app/helpers/spaces_helper.rb
module SpacesHelper
end

moneybags/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mr. Monopoly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

moneybags/app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :occupied %><br>
    <%= f.check_box :occupied %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

moneybags/app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

moneybags/app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.name %></td>
        <td><%= space.cost %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

moneybags/app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

moneybags/app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @space.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @space.cost %>
</p>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>

moneybags/app/views/welcome/index.html.erb
 <div id="main">
      <header>
        <h2>Robber Baron</h2>
        <h1>Mr. Monopoly</h1>
        <h2>Boardgame Legend</h2>
      </header>
      <p>
        Rich "Uncle" Pennybags is the round old man in a top hat who serves as the mascot of the game Monopoly. Unsuccessful attempts to rechristen Rich "Uncle" Pennybags as <a href="http://en.wikipedia.org/wiki/Rich_Uncle_Pennybags" target="_blank" title="This goes to Wikipedia">Mr. Monopoly</a> are periodically made, though most people refer to him that way. He also appears in the related games Advance to Boardwalk, Free Parking, Don't Go to Jail, Monopoly City, Monopoly Junior, and Monopoly Deal.
      </p>
      <p>
        The character first appeared on Chance and Community Chest cards in U.S. editions of Monopoly in 1936. The identity of the artist who designed the character has remained a mystery. Historian and author Philip Orbanes wrote in 2004 that it is believed that the character is based on either the calling cards of Albert Edward Richardson (Parker Brothers' first traveling salesman), the character of "Little Esky" from Esquire magazine, or a combination of the two. Orbanes later wrote, in 2006, that the character was also partially influenced by the stature and dress of financier and banker J. P. Morgan.
      </p>
      <p>
        He was named as the sixth richest fictional character in the 2006 Forbes Fictional 15 list on its website and the ninth richest in 2011.
      </p>
      <div id="spaces">
        <% @spaces.each do |space| %>
        <h4>
        <%= space.name %>: $<%= space.cost %>: <%= space.occupied %></h4>
        <% end %>

      </div>
      <a href="https://facebook.com">
        <%= image_tag "social-facebook.png" %>
      </a>
      <a href="http://flickr.com">
        <%= image_tag "social-flickr.png" %>
      </a>
      <a href="http://foursquare.com">
        <%= image_tag "social-foursquare.png" %>
  
      </a>
      <a href="http://twitter.com">
        <%= image_tag "social-twitter.png" %>
   
      </a>
    </div>